#!/usr/bin/env python3
"""Generate the coordination bridge's contract bindings (design D2).

Reads ONLY hand-authored contracts under ``openspec/contracts/`` -- never the
running application's ``app.openapi()`` -- and writes, per contract:

* ``<prefix>_models.py``: ``TypedDict`` models from the pinned
  ``datamodel-code-generator``. They need Python 3.11+, so the bridge imports
  them under ``if TYPE_CHECKING:`` only.
* ``<prefix>_operations.py``: an ``OPERATIONS`` table keyed by ``operationId``
  (method, path, path params, API-key requirement, model names). Standard
  library only and valid on Python 3.9, because skills import the bridge with
  bare ``python3``.

Output is deterministic (no timestamps, no absolute paths). ``--check`` exits
non-zero when the checked-in files differ from what the contract produces.

Run from the skills venv (``cd skills && uv sync --all-extras``)::

    skills/.venv/bin/python skills/coordination-bridge/scripts/generate_bindings.py
    skills/.venv/bin/python skills/coordination-bridge/scripts/generate_bindings.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_DIR = SCRIPT_DIR / "_generated"
REGENERATE_COMMAND = (
    "skills/.venv/bin/python skills/coordination-bridge/scripts/generate_bindings.py"
)

# Contract (relative to the repo root) -> module prefix in _generated/.
CONTRACTS: tuple[tuple[str, str], ...] = (
    ("openspec/contracts/agent-coordinator/openapi/features.yaml", "features"),
)

# Pinned in skills/pyproject.toml (test extra). Formatters are named explicitly
# because datamodel-codegen warns its defaults will change.
DATAMODEL_CODEGEN_ARGS = (
    "--input-file-type",
    "openapi",
    "--output-model-type",
    "typing.TypedDict",
    "--target-python-version",
    "3.11",
    "--disable-timestamp",
    "--formatters",
    "black",
    "isort",
    "--use-schema-description",
)

_HTTP_METHODS = ("get", "put", "post", "delete", "patch", "head", "options", "trace")


def _header(contract_rel: str) -> str:
    return f"# GENERATED by generate_bindings.py from {contract_rel} — do not edit\n"


def find_repo_root(start: Path = SCRIPT_DIR) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "openspec" / "contracts").is_dir():
            return candidate
    raise SystemExit("generate_bindings: no openspec/contracts/ above " + start.name)


def render_models(repo_root: Path, contract_rel: str) -> str:
    # Relative input path + cwd at the repo root keep datamodel-codegen's
    # "filename:" header free of absolute paths.
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            contract_rel,
            *DATAMODEL_CODEGEN_ARGS,
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(f"datamodel-codegen failed for {contract_rel}:\n{result.stderr}")
    return _header(contract_rel) + result.stdout


def _ref_name(schema: Any, where: str) -> str:
    if not isinstance(schema, dict) or "$ref" not in schema:
        raise SystemExit(f"generate_bindings: {where} must be a $ref to a named schema")
    return str(schema["$ref"]).rsplit("/", 1)[-1]


def _requires_api_key(op: dict[str, Any], doc: dict[str, Any]) -> bool:
    security = op["security"] if "security" in op else doc.get("security", [])
    schemes = doc.get("components", {}).get("securitySchemes", {})
    # Every alternative must name an apiKey scheme; an empty alternative ({})
    # means anonymous access is allowed.
    return bool(security) and all(
        any(schemes.get(name, {}).get("type") == "apiKey" for name in requirement)
        for requirement in security
    )


def _operation_entry(
    method: str, path: str, path_item: dict[str, Any], op: dict[str, Any], doc: dict[str, Any]
) -> dict[str, Any]:
    op_id = op["operationId"]
    path_params = tuple(re.findall(r"{([^}]+)}", path))
    declared = {
        p["name"]
        for p in (*path_item.get("parameters", []), *op.get("parameters", []))
        if p.get("in") == "path"
    }
    if declared != set(path_params):
        raise SystemExit(
            f"generate_bindings: {op_id} path params {sorted(path_params)} "
            f"do not match declared parameters {sorted(declared)}"
        )

    body = op.get("requestBody", {}).get("content", {}).get("application/json")
    request_model = _ref_name(body.get("schema"), f"{op_id} request body") if body else None

    success = sorted(str(code) for code in op.get("responses", {}) if str(code).startswith("2"))
    response_model = None
    if success:
        content = op["responses"][success[0]].get("content", {}).get("application/json")
        if content:
            response_model = _ref_name(content.get("schema"), f"{op_id} {success[0]} response")

    return {
        "method": method.upper(),
        "path": path,
        "path_params": path_params,
        "requires_api_key": _requires_api_key(op, doc),
        "request_model": request_model,
        "response_model": response_model,
    }


def _literal(value: Any) -> str:
    """Python literal in black's style (double quotes, trailing comma in tuples)."""
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, tuple):
        return "(" + "".join(f"{_literal(v)}, " for v in value).rstrip(" ") + ")"
    return repr(value)


def render_operations(repo_root: Path, contract_rel: str) -> str:
    doc = yaml.safe_load((repo_root / contract_rel).read_text(encoding="utf-8"))
    entries: dict[str, dict[str, Any]] = {}
    for path, path_item in doc.get("paths", {}).items():
        for method in _HTTP_METHODS:
            op = path_item.get(method)
            if isinstance(op, dict) and "operationId" in op:
                entries[op["operationId"]] = _operation_entry(method, path, path_item, op, doc)

    lines = [
        _header(contract_rel).rstrip("\n"),
        '"""Operation table generated from the contract.',
        "",
        "Standard library only and valid on Python 3.9: the coordination bridge",
        "imports this at runtime under bare ``python3``.",
        '"""',
        "",
        "from typing import Dict, NamedTuple, Optional, Tuple",
        "",
        "",
        "class Operation(NamedTuple):",
        "    method: str",
        "    path: str",
        "    path_params: Tuple[str, ...]",
        "    requires_api_key: bool",
        "    request_model: Optional[str]",
        "    response_model: Optional[str]",
        "",
        "",
        "OPERATIONS: Dict[str, Operation] = {",
    ]
    for op_id in sorted(entries):
        entry = entries[op_id]
        lines.append(f"    {_literal(op_id)}: Operation(")
        for field, value in entry.items():
            lines.append(f"        {field}={_literal(value)},")
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_package_init() -> str:
    contracts = ", ".join(rel for rel, _ in CONTRACTS)
    return _header(contracts) + '"""Contract-generated bindings for the coordination bridge."""\n'


def render_all(repo_root: Path) -> dict[str, str]:
    files = {"__init__.py": render_package_init()}
    for contract_rel, prefix in CONTRACTS:
        files[f"{prefix}_models.py"] = render_models(repo_root, contract_rel)
        files[f"{prefix}_operations.py"] = render_operations(repo_root, contract_rel)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the checked-in bindings are stale; write nothing",
    )
    parser.add_argument("--repo-root", type=Path, help="directory holding openspec/contracts/")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)

    repo_root = (args.repo_root or find_repo_root()).resolve()
    files = render_all(repo_root)

    if args.check:
        stale = [
            name
            for name, content in files.items()
            if not (args.output_dir / name).is_file()
            or (args.output_dir / name).read_text(encoding="utf-8") != content
        ]
        if stale:
            for name in stale:
                print(f"stale: {args.output_dir / name}")
            print(f"regenerate with: {REGENERATE_COMMAND}")
            return 1
        print("bindings are current")
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (args.output_dir / name).write_text(content, encoding="utf-8")
        print(f"wrote {args.output_dir / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
