# GENERATED by generate_bindings.py from openspec/contracts/agent-coordinator/openapi/features.yaml — do not edit
"""Operation table generated from the contract.

Standard library only and valid on Python 3.9: the coordination bridge
imports this at runtime under bare ``python3``.
"""

from typing import Dict, NamedTuple, Optional, Tuple


class Operation(NamedTuple):
    method: str
    path: str
    path_params: Tuple[str, ...]
    requires_api_key: bool
    request_model: Optional[str]
    response_model: Optional[str]


OPERATIONS: Dict[str, Operation] = {
    "analyzeFeatureConflicts": Operation(
        method="POST",
        path="/features/conflicts",
        path_params=(),
        requires_api_key=True,
        request_model="FeatureConflictsRequest",
        response_model="ConflictReport",
    ),
    "deregisterFeature": Operation(
        method="POST",
        path="/features/deregister",
        path_params=(),
        requires_api_key=True,
        request_model="FeatureDeregisterRequest",
        response_model="FeatureDeregisterResult",
    ),
    "getFeature": Operation(
        method="GET",
        path="/features/{feature_id}",
        path_params=("feature_id",),
        requires_api_key=True,
        request_model=None,
        response_model="FeatureDetail",
    ),
    "listActiveFeatures": Operation(
        method="GET",
        path="/features/active",
        path_params=(),
        requires_api_key=True,
        request_model=None,
        response_model="ActiveFeaturesEnvelope",
    ),
    "registerFeature": Operation(
        method="POST",
        path="/features/register",
        path_params=(),
        requires_api_key=True,
        request_model="FeatureRegisterRequest",
        response_model="FeatureRegisterResult",
    ),
}
