"""A producer's report is identical for relative and absolute repository paths.

ri-10 task 6.1, design D12.

``tree_diff`` carries an unstated precondition: **a renderer's output must not
depend on its input paths.** A renderer that interpolates the paths it was handed
into its output produces a tempdir render that can never byte-match the committed
tree, and the producer reports that as *staleness* — a diagnosis that sends the
reader looking for a stale artifact instead of a broken renderer. That is exactly
how ``decisions.timeline`` came to report 17 stale files on a tree whose
``docs/decisions/`` was provably fresh.

The guard is written over ``registry.list_producers()`` rather than over the one
producer that failed it, because the precondition belongs to every tempdir-diff
producer, current and future, and one enumerating test is cheaper than auditing
each renderer. ``TestTheAssertionCanFail`` registers a deliberately
path-dependent producer and requires the assertion to catch and name it, so a
vacuous version of this module fails its own suite.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
from typing import Any

import pytest

import results as R
from _runtime import ProducerStatus, Remediation
from registry import Producer, ProducerSpec, list_producers, register, run_producer
from tree_diff import diff_trees

_CAPABILITY = "software-factory-tooling"


# --------------------------------------------------------------------------- #
# The assertion
# --------------------------------------------------------------------------- #
def report_for(repository: Path, revision: str) -> dict[str, dict[str, Any]]:
    """Run every registered producer in check mode; return report dicts by id.

    ``ProducerResult.to_dict`` is fully content-derived — it carries no clock, no
    duration, and no path outside the repository — so equality between two dicts
    is equality of the whole report.
    """
    specs = list_producers()
    assert specs, "the registry exposed no producers; the assertion would be vacuous"
    return {
        spec.producer_id: run_producer(spec.producer_id, "check", repository, revision).to_dict()
        for spec in specs
    }


def _artifact_summary(report: dict[str, Any]) -> list[str]:
    """``path change sha256[:12]`` per artifact — the digest is what usually differs."""
    return [
        f"{a['path']} {a['change']} {(a['sha256'] or 'none')[:12]}"
        for a in report["artifacts"]
    ]


def assert_reports_are_path_independent(
    repository_root: Path, revision: str
) -> dict[str, dict[str, Any]]:
    """Assert each producer reports identically for a relative and absolute path.

    *repository_root* must be a path relative to the current working directory.
    Raises ``AssertionError`` naming the offending producer, so a failure points
    at a renderer rather than at a diff.
    """
    assert not repository_root.is_absolute(), (
        "pass a relative repository path; comparing two absolute spellings would "
        "not exercise the precondition"
    )
    relative_reports = report_for(repository_root, revision)
    absolute_reports = report_for(repository_root.resolve(), revision)

    assert sorted(relative_reports) == sorted(absolute_reports)
    for producer_id, relative in relative_reports.items():
        absolute = absolute_reports[producer_id]
        if relative == absolute:
            continue
        relative_artifacts = _artifact_summary(relative)
        absolute_artifacts = _artifact_summary(absolute)
        raise AssertionError(
            f"producer {producer_id!r} reported differently for a relative and an "
            "absolute repository path, so its renderer's output depends on its "
            "input paths — that is a producer defect, not staleness.\n"
            f"  relative: status={relative['status']} artifacts={relative_artifacts}\n"
            f"  absolute: status={absolute['status']} artifacts={absolute_artifacts}"
        )
    return relative_reports


# --------------------------------------------------------------------------- #
# Fixture: a committed checkout carrying every producer's inputs
# --------------------------------------------------------------------------- #
def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _managed(title: str, block_id: str, body: str) -> str:
    """A marker-managed inventory file, matching ``inventory_file._skeleton``."""
    return (
        f"# {title}\n\n"
        "<!-- This file is generated by a project-context producer. Edit prose "
        "outside the generated markers only; content inside the markers is "
        "overwritten on regeneration. -->\n\n"
        f"<!-- GENERATED: begin {block_id} -->\n"
        f"{body}\n"
        f"<!-- GENERATED: end {block_id} -->\n"
    )


def _seed_decision_index(repo: Path) -> None:
    """Commit the decision index as the canonical owner renders it.

    Seeded through the owner from a *relative* archive root — the spelling
    ``make decisions`` uses — so ``check`` has a real committed tree to compare
    against and ``decisions.timeline`` reports ``fresh`` rather than trivially
    reporting every file as added.
    """
    import sys

    owner_scripts = (
        Path(__file__).resolve().parents[2] / "explore-feature" / "scripts"
    )
    if str(owner_scripts) not in sys.path:
        sys.path.insert(0, str(owner_scripts))
    from archive_index import emit_decisions_from_archive

    cwd = Path.cwd()
    try:
        import os

        os.chdir(repo)
        emit_decisions_from_archive(
            archive_root=Path("openspec") / "changes",
            output_dir=Path("docs") / "decisions",
            capabilities_root=Path("openspec") / "specs",
            strict=False,
        )
    finally:
        import os

        os.chdir(cwd)


@pytest.fixture
def checkout(tmp_path: Path) -> tuple[Path, Path, str]:
    """Return ``(parent_dir, relative_repo_path, head_sha)``.

    Every producer must find real inputs and a committed output to compare
    against: a producer that bails out early would make the comparison prove
    nothing. Two marker inventories are committed deliberately stale so those
    producers report drift, and the decision index is committed fresh so
    ``decisions.timeline`` exercises the byte comparison rather than the
    everything-is-new path.
    """
    repo = tmp_path / "checkout"
    repo.mkdir()
    subprocess.run(["git", "init", str(repo)], check=True, capture_output=True)
    for key, value in (("user.email", "t@example.com"), ("user.name", "T")):
        _git(repo, "config", key, value)

    # documentation.inventory
    _write(
        repo / "skills" / "alpha" / "SKILL.md",
        "---\nname: alpha\nuser_invocable: true\ndescription: First skill\n---\n\nBody\n",
    )
    _write(
        repo / "docs" / "architecture-analysis" / "skills-inventory.md",
        _managed("Skills inventory", "skills-inventory", "_stale body_"),
    )

    # api.contracts
    _write(
        repo / "openspec" / "contracts" / "cap" / "schemas" / "thing.schema.json",
        '{\n  "$id": "thing.schema.json",\n  "title": "Thing",\n  "type": "object"\n}\n',
    )
    _write(
        repo / "docs" / "architecture-analysis" / "contracts-inventory.md",
        _managed("Contracts inventory", "contracts-inventory", "_stale body_"),
    )

    # openspec.projection: a canonical spec plus an active change delta over it.
    _write(
        repo / "openspec" / "specs" / "cap" / "spec.md",
        "# cap\n\n## Requirements\n\n### Requirement: Existing\n\nThe system SHALL exist.\n",
    )
    _write(
        repo / "openspec" / "changes" / "live-change" / "specs" / "cap" / "spec.md",
        "## ADDED Requirements\n\n### Requirement: New\n\nThe system SHALL be new.\n",
    )
    _write(repo / "openspec" / "changes" / "live-change" / "proposal.md", "# live-change\n")

    # decisions.timeline: archived session logs carrying tagged decisions.
    _write(repo / "openspec" / "specs" / _CAPABILITY / "spec.md", f"# {_CAPABILITY}\n")
    _write(
        repo / "openspec" / "changes" / "archive" / "2026-01-05-first" / "session-log.md",
        "# Session Log — first\n"
        "\n"
        "## Phase: Plan (2026-01-05)\n"
        "\n"
        "### Decisions\n"
        "\n"
        f"1. **Pin worktrees while idle** `architectural: {_CAPABILITY}` — GC would "
        "reclaim them mid-pause\n",
    )
    _write(
        repo / "openspec" / "changes" / "archive" / "2026-02-09-second" / "session-log.md",
        "# Session Log — second\n"
        "\n"
        "## Phase: Implementation (2026-02-09)\n"
        "\n"
        "### Decisions\n"
        "\n"
        f"1. **Use `--` as the branch separator** `architectural: {_CAPABILITY}` — git "
        "refuses nested ref names\n",
    )
    _seed_decision_index(repo)

    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "init")
    head = _git(repo, "rev-parse", "HEAD")
    return tmp_path, Path("checkout"), head


# --------------------------------------------------------------------------- #
# Scenario: Path dependence is detected as a defect, not as staleness
# --------------------------------------------------------------------------- #
class TestEveryProducerIsPathIndependent:
    def test_the_fixture_gives_the_decisions_producer_real_work(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        """A committed index rendered by the owner is what makes the diff real."""
        parent, repo, head = checkout
        monkeypatch.chdir(parent)

        index = repo / "docs" / "decisions"
        rendered = sorted(p.name for p in index.glob("*.md"))
        assert f"{_CAPABILITY}.md" in rendered
        assert "README.md" in rendered

        result = run_producer("decisions.timeline", "check", repo, head)
        assert result.status is ProducerStatus.FRESH, (
            "the committed index does not match a relative render, so the "
            f"comparison below would not be exercised: {result.to_dict()}"
        )

    def test_every_registered_producer_reports_identically(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        parent, repo, head = checkout
        monkeypatch.chdir(parent)

        reports = assert_reports_are_path_independent(repo, head)

        assert sorted(reports) == [spec.producer_id for spec in list_producers()]
        assert all(
            report["status"] != ProducerStatus.FAILED.value for report in reports.values()
        ), reports

    def test_the_producers_compared_something(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        """Identical reports from producers that never ran is not evidence."""
        parent, repo, head = checkout
        monkeypatch.chdir(parent)

        reports = report_for(repo, head)

        assert any(report["validations"] for report in reports.values())
        # The two marker inventories were committed stale on purpose.
        assert any(
            report["status"] == ProducerStatus.DEGRADED.value for report in reports.values()
        ), reports

    def test_the_enumeration_is_the_registry_not_a_literal_list(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        parent, repo, head = checkout
        monkeypatch.chdir(parent)
        register(_PathIndependentProducer("zz.registered-later"))

        reports = assert_reports_are_path_independent(repo, head)

        assert "zz.registered-later" in reports
        assert set(reports) == {spec.producer_id for spec in list_producers()}


# --------------------------------------------------------------------------- #
# Mutation proof: the assertion must be able to fail
# --------------------------------------------------------------------------- #
class _TempdirDiffProducer(Producer):
    """A tempdir-diff producer whose render optionally embeds the repository path."""

    _PREFIX = "docs/fixture"

    def __init__(self, producer_id: str, *, path_dependent: bool) -> None:
        self.spec = ProducerSpec(
            producer_id=producer_id,
            producer_version="1",
            owner="mutation-fixture",
            inputs=(),
            outputs=(f"{self._PREFIX}/",),
        )
        self._path_dependent = path_dependent

    def run(self, mode, repository, source_revision):  # noqa: ANN001
        repository = Path(repository)
        committed = repository / self._PREFIX
        with tempfile.TemporaryDirectory() as tmp:
            rendered = Path(tmp)
            body = f"repository: {repository}\n" if self._path_dependent else "fixed\n"
            (rendered / "rendered.md").write_text(body, encoding="utf-8")
            artifacts = diff_trees(
                committed, rendered, path_prefix=self._PREFIX, patterns=("*.md",)
            )
        if artifacts:
            return R.drift(
                self.spec.producer_id,
                self.spec.producer_version,
                artifacts=artifacts,
                validations=[R.failed_validation("fixture", "fixture output is stale")],
                remediation=[Remediation(summary="fixture")],
            )
        return R.fresh(
            self.spec.producer_id,
            self.spec.producer_version,
            validations=[R.passed("fixture", "fixture output is current")],
        )


class _PathIndependentProducer(_TempdirDiffProducer):
    def __init__(self, producer_id: str) -> None:
        super().__init__(producer_id, path_dependent=False)


class TestTheAssertionCanFail:
    def test_a_path_dependent_renderer_is_caught_and_named(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        parent, repo, head = checkout
        monkeypatch.chdir(parent)
        register(_TempdirDiffProducer("zz.path-dependent", path_dependent=True))

        with pytest.raises(AssertionError) as excinfo:
            assert_reports_are_path_independent(repo, head)

        message = str(excinfo.value)
        assert "zz.path-dependent" in message
        assert "producer defect, not staleness" in message

    def test_a_path_independent_renderer_passes(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        """The fixture pair differs only in path dependence, so the mutation is the cause."""
        parent, repo, head = checkout
        monkeypatch.chdir(parent)
        register(_TempdirDiffProducer("zz.path-independent", path_dependent=False))

        reports = assert_reports_are_path_independent(repo, head)

        assert reports["zz.path-independent"]["status"] == ProducerStatus.DEGRADED.value

    def test_the_assertion_rejects_an_absolute_repository_argument(
        self, checkout: tuple[Path, Path, str], monkeypatch
    ) -> None:
        """Two absolute spellings would compare a path against itself."""
        parent, repo, head = checkout
        monkeypatch.chdir(parent)

        with pytest.raises(AssertionError, match="relative repository path"):
            assert_reports_are_path_independent((parent / repo).resolve(), head)
